volumes:
  mysql-data:
networks:
  spring-boot-mysql-network:
    name: spring-boot-mysql-network
services:
  mysqldb:
    image: mysql:lts
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=techstore
      - MYSQL_USER=techstore_user
      - MYSQL_PASSWORD=Yni7BBCt9FZlaHGvjY8G9L+Tv+5nswkBbzXFkS4jOeM=
      - MYSQL_ROOT_PASSWORD=56KfuqWhu0KaAJMbEdVTjJCKDAW7U1P8kdJB8vevwX8=
    networks:
      - spring-boot-mysql-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 30s
      retries: 5
  techstore:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/techstore
      - SPRING_DATASOURCE_USERNAME=techstore_user
      - SPRING_DATASOURCE_PASSWORD=Yni7BBCt9FZlaHGvjY8G9L+Tv+5nswkBbzXFkS4jOeM=
    networks:
      - spring-boot-mysql-network
